### ISSUE TITLE
Doesn't work in Chrome 75.0.3770.100 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by insider89** [tilfin/aws-extend-switch-roles#99]
Yesterday I was updated my Chrome to latest 75.0.3770.100 (Official Build) (64-bit), and switcher stops to work. I don't see any history when this extension enables. When I disable it, I can see my history.

**Comment by tilfin** [comment]
@insider89 I just released the new version yesterday. It may be related to **Fix excluding unrelated profiles from role history**. Can you see your settings you have modified to make them public?

**Comment by tilfin** [comment]
and you may be able to fix it by changing the checkbox option on the configuration screen and saving the configuration text again.

**Comment by insider89** [comment]
I didn't change my configuration but have latest version of the extension. Not sure what you mean "to make them public", could you please clarify. 
My configuration looks like that:
```
[profile iam]
region = eu-west-1
aws_account_id = XXXXXX

[profile iam-admin]
region=eu-west-1
role_arn=arn:aws:iam::XXXXXX:role/role_admin
source_profile=iam
color = ff2600
```

I've tried to set every checkbox one by one, but it does not fix the problem.

**Comment by tilfin** [comment]
Thanks, I tried your setting, but I have no problem in particular. Are the 6 profiles the almost same definition? Does it not change even if you try to reduce them?

**Comment by justcompile** [comment]
I am also seeing the same problem. I have 16 profiles & I can only see the 5 most recently switched to. It only appears to be showing the original history, not that configured in this extension

**Comment by insider89** [comment]
I have a number in profile names, and it doesn't work with it. With numbers in profile names I don't see any role to switch in aws console.
```profile 100xxx-iam]
region = eu-west-1
aws_account_id = XXXXXX

[profile 100xxx-iam-admin]
region=eu-west-1
role_arn=arn:aws:iam::XXXXXX:role/role_admin
source_profile=100xxx-iam
color = ff2600
```

When I remove `100xxx-` I see old history in AWS console with numbers on profile, but not I have configured. So if I change to the following:
```
[profile iam]
region = eu-west-1
aws_account_id = XXXXXX

[profile iam-admin]
region=eu-west-1
role_arn=arn:aws:iam::XXXXXX:role/role_admin
source_profile=iam
color = ff2600
```

In aws console I see `100xxx-iam-admin`, but should be `iam-admin`

**Comment by ouroboros8** [comment]
I'm also having this problem with Firefox 67.0.3 (64-bit)

**Comment by ouroboros8** [comment]
Specifically, as of this update, none of the configured profiles appear in my switch-role menu:

<img width="232" alt="image" src="https://user-images.githubusercontent.com/6664881/60009753-4fbf0b00-966e-11e9-9921-b1b2d3193a0d.png">

**Comment by tilfin** [comment]
There are things that I want to try and things I want to confirm.

1. Please set to check `Hide original role history` in the Settings. Because the profile history when it was broken may be adversely affected.

2. Does your setting have the duplicate same profile name? The profile names must be unique in the whole, even for entries for different source profiles.

**Comment by ouroboros8** [comment]
I have hide original role history enabled and there are no duplicate names. Have done some troubleshooting and for me it appears to be this set of profiles that breaks the config:

```
[acc1-login]
aws_account_id = 1234

[acc1]
role_arn = arn:aws:iam::1234:role/myrole
source_profile = acc1-login
color = cc241d
```

the idea here is that acc1-login is the source_profile for most of my other profiles, and acc1 assumes a specific administrative role in that account (my user has only IAM privileges in that account so assume role is required to actually do things)

Is there a chance that assuming role within the same account is broken in this update?

**Comment by insider89** [comment]
@tilfin 
1. Doesn't help - switch role history still empty
2. No duplication in profiles name

**Comment by tilfin** [comment]
Thanks, everyone!
I confirmed this issue where the switch role definition in the same AWS Account ID causes the list to be empty. I am fixing it for new version 0.13.1.

**Comment by ouroboros8** [comment]
Awesome, thanks @tilfin :)

**Comment by rngtng** [comment]
I've run in this problem again with latest chrome and version 0.14. Even the exmaple in README.md doesn't display any roles:

```
[organization1]
aws_account_id = your-account-alias

[Org1-Account1-Role1]
role_arn = arn:aws:iam::123456789012:role/Role1
source_profile = organization1
```

I'm able to trace it back to `source_profile` attribute. once this is removed, all works. Any ideas what's wrong? Thx
